project:
  type: book

book:
  title: "test-quarto-book2"
  author: "Norah Jones"
  date: "9/24/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
  references: references.qmd
  appendices:
    - appendix1.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  docx:
    fig-align: "center"
    cap-location: top
    fig-cap-location: top
    tbl-cap-location: top
    fig-height: 8
    fig-width: 7
    toc: true
    echo: false
    mainfont: serif
    fig-dpi: 600
    markdown: true

editor: visual

